if(DEFINED _TOOLCHAIN_FLAGS_FUNCTION_SECTIONS)
  return()
else()
  set(_TOOLCHAIN_FLAGS_FUNCTION_SECTIONS 1)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../_utilities/_add_cache_flags.cmake")
if(_not_android)
  _add_cache_flags(CMAKE_CXX_FLAGS "-ffunction-sections")
  _add_cache_flags(CMAKE_C_FLAGS "-ffunction-sections")
else()
  _add_cache_flags(CMAKE_CXX_FLAGS_INIT "-ffunction-sections")
  _add_cache_flags(CMAKE_C_FLAGS_INIT "-ffunction-sections")
endif()
