if(DEFINED _TOOLCHAIN_FLAGS_COMMON)
  return()
else()
  set(_TOOLCHAIN_FLAGS_COMMON 1)
endif()

if(NOT TOOLCHAIN_GNU_STANDARD)
  if(TOOLCHAIN_C_STANDARD)
    if(CMAKE_GENERATOR MATCHES "^Visual Studio*$")
      include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_vs_c.cmake")
    else()
      include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_c.cmake")
    endif()
  endif()
else()
  include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_gnu.cmake")
endif()

if(NOT TOOLCHAIN_GNUXX_STANDARD)
  if(TOOLCHAIN_CXX_STANDARD)
    if(CMAKE_GENERATOR MATCHES "^Visual Studio*$")
      include("${CMAKE_CURRENT_LIST_DIR}/../../_flags/_vs_cxx.cmake")
    else()
      include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_cxx.cmake")
    endif()
  endif()
else()
  include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_gnuxx.cmake")
endif()

if(CMAKE_GENERATOR MATCHES "^Visual Studio*$")

else()
  if(_TOOLCHAIN_FPIC)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_fpic.cmake")
  endif()

  if(_TOOLCHAIN_HIDDEN)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_hidden.cmake")
  endif()

  if(_TOOLCHAIN_FSECTIONS)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_function_sections.cmake")
  endif()

  if(_TOOLCHAIN_DSECTIONS)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_data_sections.cmake")
  endif()

  if(_TOOLCHAIN_STATIC)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_static.cmake")
  endif()

  if(_TOOLCHAIN_STATIC_STD)
    include("${CMAKE_CURRENT_LIST_DIR}/../_flags/_static_std.cmake")
  endif()
endif()